use bodyShort or empty string if bodyLong doesn't exist
crash fix for 
```
TypeError: Cannot call method 'replace' of undefined
    at S.unescapeHTML (/var/www/community.nodebb.org/node_modules/string/lib/string.js:569:42)
    at async.waterfall.payload.device_iden (/var/www/community.nodebb.org/node_modules/nodebb-plugin-pushbullet/library.js:150:45)
    at fn (/var/www/community.nodebb.org/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/var/www/community.nodebb.org/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```